import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    dashboard: 'Dashboard',
    cropRecommendation: 'Crop Recommendation',
    fertilizerGuide: 'Fertilizer Guide',
    weather: 'Weather Insights',
    askExpert: 'Expert Consultation',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    welcomeMessage: 'Welcome to Smart Crop Advisory System',
    heroTitle: 'Empowering Farmers with Smart Agricultural Solutions',
    heroSubtitle: 'Get personalized crop recommendations, weather insights, and expert guidance',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    features: 'Features',
    aboutUs: 'About Us',
    contact: 'Contact',
    allRightsReserved: 'All rights reserved',

    // Footer
    brandName: 'Smart Crop Advisory',
    brandDesc: 'Empowering farmers with technology-driven agricultural solutions for sustainable farming.',
    quickLinks: 'Quick Links',
    adminLogin: 'Admin Login',
    servicesTitle: 'Services',

    // Dashboard
    advisoryTools: 'Your Advisory Tools',
    todaysTips: "Today's Farming Tips",
    tip1: 'Check soil moisture before irrigation to save water and improve crop yield',
    tip2: 'Monitor weather forecasts regularly to plan your agricultural activities',
    tip3: 'Use organic fertilizers to improve soil health and reduce chemical dependency',
    farmAnalytics: 'Farm Analytics',
    cropCalendar: 'Crop Calendar',
    comingSoon: 'Coming Soon',
    stateLabel: 'State',
    districtLabel: 'District',
    statusLabel: 'Status',
    statusActive: '✅ Active',

    // Card descriptions
    cropRecommendationDesc: 'Get AI-powered crop suggestions based on your soil and location',
    fertilizerGuideDesc: 'Optimal NPK ratios and organic fertilizer recommendations',
    weatherDesc: 'Real-time weather updates and 7-day forecasts',
    askExpertDesc: 'Get answers from agricultural experts',
    farmAnalyticsDesc: 'Track your farm performance and insights',
    cropCalendarDesc: 'Plan your agricultural activities',

    // Home page
    empoweringTitle: "Empowering India's Farmers 🇮🇳",
    empoweringDesc1: 'Agriculture is the backbone of our nation, yet farmers often lack access to timely information about crop selection, weather patterns, and fertilizer usage.',
    empoweringDesc2: 'Our mission is to bridge this gap with technology, providing farmers with data-driven insights that increase yield, reduce costs, and promote sustainable farming practices.',
    featuresSubtitle: 'Comprehensive tools designed specifically for Indian farmers',
    ctaTitle: 'Ready to Transform Your Farming? 🌾',
    connectPeersDesc: 'Join discussions with farmers across India',
    predictYield: 'Yield Predictor (ML)',
    predictYieldDesc: 'Mathematical estimation of crop production',
    detectDisease: 'Plant Disease Identifier',
    detectDiseaseDesc: 'Upload a leaf photo for AI pathology analysis',
    ctaSubtitle: 'Join thousands of farmers already benefiting from smart agricultural solutions',
    ctaButton: 'Start Your Journey Today',

    // Home feature descriptions
    cropRecommendationHomeDesc: 'Get AI-powered crop suggestions based on your soil type and location',
    fertilizerGuideHomeDesc: 'Optimal NPK ratios and organic fertilizer recommendations',
    weatherHomeDesc: 'Real-time weather updates and 7-day forecasts for your region',
    askExpertHomeDesc: 'Get answers from agricultural experts for your farming queries',
    communitySupport: 'Community Support',
    communitySupportDesc: 'Connect with fellow farmers and share best practices',
    dataSecurity: 'Data Security',
    dataSecurityDesc: 'Your farming data is secure and protected with us',

    // CropRecommendation page
    cropPageTitle: 'Crop Recommendation System 🌱',
    cropPageSubtitle: 'Get AI-powered crop suggestions based on your soil and location',
    enterFarmDetails: 'Enter Your Farm Details',
    soilTypeLabel: 'Soil Type',
    selectSoilType: 'Select your soil type',
    selectState: 'Select your state',
    getCropRec: 'Get Crop Recommendations',
    gettingRec: 'Getting Recommendations...',
    recommendedCrops: 'Recommended Crops 🌾',
    cropsFound: 'crops found',
    cropName: 'Crop Name',
    season: 'Season',
    waterReq: 'Water Requirement',
    duration: 'Duration',
    expectedYield: 'Expected Yield',
    cropRotationTip: 'Tip: Consider crop rotation to maintain soil health and prevent pest buildup. Diversifying crops also helps in managing market risks.',

    // FertilizerGuide page
    fertPageTitle: 'Fertilizer Guide 💧',
    fertPageSubtitle: 'Get optimal NPK ratios and organic fertilizer recommendations',
    selectYourCrop: 'Select Your Crop',
    cropType: 'Crop Type',
    selectCropPlaceholder: 'Select crop for fertilizer recommendation',
    getFertGuide: 'Get Fertilizer Guide',
    gettingFertRec: 'Getting Recommendations...',
    npkRequirements: 'NPK Requirements for',
    nitrogen: 'Nitrogen',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    organicFertRec: 'Organic Fertilizer Recommendation',
    organicManureTip: 'Apply organic manure to improve soil structure and microbial activity',
    applicationTips: '🌱 Application Tips:',
    fertTip1: 'Apply fertilizers in split doses for better nutrient uptake',
    fertTip2: 'Ensure soil moisture is adequate before fertilizer application',
    fertTip3: 'Mix organic and chemical fertilizers for balanced nutrition',
    fertTip4: 'Apply fertilizers 5-7 cm away from plant base to avoid root burn',
    importantPrecautions: '⚠️ Important Precautions:',
    precaution1: 'Always conduct soil testing before fertilizer application',
    precaution2: 'Avoid over-fertilization as it can harm crops and soil',
    precaution3: 'Use protective gear when handling chemical fertilizers',
    precaution4: 'Store fertilizers in a cool, dry place away from moisture',

    // Weather page
    weatherPageTitle: 'Weather Information 🌦️',
    weatherPageSubtitle: 'Get real-time weather updates and forecasts for your region',
    enterLocation: 'Enter Your Location',
    districtName: 'District Name',
    enterDistrict: 'Enter your district name',
    getWeather: 'Get Weather Information',
    gettingWeather: 'Getting Weather Data...',
    currentWeather: 'Current Weather',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainfall: 'Rainfall',
    forecast: '3-Day Forecast',
    weatherFarmTip: 'Farming Tip: Plan your irrigation and spraying activities based on the weather forecast. Avoid applying pesticides before expected rainfall.',

    // AskExpert page
    askPageTitle: 'Ask an Expert 🎤',
    askPageSubtitle: 'Get answers from agricultural experts for your farming queries',
    submitQuery: 'Submit Your Query',
    expertResponseTime: 'Our agricultural experts will review and respond to your question within 24-48 hours',
    yourName: 'Your Name',
    yourDistrict: 'District',
    yourQuestion: 'Your Question',
    questionPlaceholder: 'Describe your agricultural query in detail. For example: What is the best irrigation method for wheat in clay soil?',
    questionRequired: 'Please enter your question',
    questionMinLength: 'Question must be at least 20 characters',
    questionMaxLength: 'Question must not exceed 1000 characters',
    submittingQuery: 'Submitting Query...',
    submitToExpert: 'Submit Query to Expert',
    betterResponsesTips: '💡 Tips for Better Responses:',
    queryTip1: 'Be specific about your crop, soil type, and region',
    queryTip2: "Include details about the problem or issue you're facing",
    queryTip3: "Mention any practices you've already tried",
    queryTip4: 'Ask one main question at a time for clearer answers',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'How long does it take to get a response?',
    faq1A: 'Typically within 24-48 hours. Urgent queries are prioritized.',
    faq2Q: 'Can I ask multiple questions?',
    faq2A: 'Yes, but we recommend asking one main question per submission for better clarity.',
    faq3Q: 'What types of questions can I ask?',
    faq3A: 'Any agriculture-related queries: crop selection, pest control, soil management, irrigation, etc.',
    querySuccessTitle: 'Query Submitted Successfully! 🎉',
    querySuccessDesc: 'Your query has been submitted to our agricultural experts. You will receive a detailed response within 24-48 hours at your registered contact details.',
    gotIt: 'Got it!',
    
    // My Queries
    myQueriesTitle: 'Your Past Queries',
    statusPending: 'Pending',
    statusAnswered: 'Answered',
    adminResponse: 'Expert Response:',
    noQueriesFound: "You haven't submitted any queries yet.",

    // Crop Calendar
    calendarPageTitle: 'Crop Calendar',
    calendarPageSubtitle: 'Plan your agricultural activities month by month',
    selectCropCalendar: 'Select Crop',
    cropCalendarPlaceholder: 'Select a crop to view calendar',
    viewCalendar: 'View Calendar',
    sowingPhase: 'Sowing Phase',
    growingPhase: 'Growing Phase',
    harvestingPhase: 'Harvesting Phase',
    activities: 'Key Activities',
    noCalendarData: 'No calendar data available for this crop.',

    // About page
    aboutOurStory: 'Our Story',
    aboutHeroTitle: 'About Smart Crop Advisory 🌾',
    aboutHeroSubtitle: "Born out of a deep respect for India's farming heritage and a belief that technology can transform lives — we exist to put the right information in every farmer's hands.",
    aboutOurMission: 'Our Mission',
    aboutMissionText: 'To democratise agricultural knowledge by delivering personalised, data-driven insights to every farmer in India — regardless of their location, education, or resources.',
    aboutOurVision: 'Our Vision',
    aboutVisionText: 'A future where no Indian farmer struggles with crop loss due to lack of timely advice. We envision technology as the great equaliser in rural agriculture.',
    aboutImpactTitle: 'Our Impact in Numbers 📊',
    statFarmersHelped: 'Farmers Helped',
    statStatesCovered: 'States Covered',
    statYieldIncrease: 'Avg. Yield Increase',
    statSatisfaction: 'Satisfaction Rate',
    aboutValuesTitle: 'What We Stand For ✨',
    aboutValuesSubtitle: 'Our core values guide every decision we make and every product we build.',
    valueSustainability: 'Sustainability',
    valueSustainabilityDesc: 'We champion eco-friendly farming practices that protect the environment while maximising productivity for future generations.',
    valueInnovation: 'Innovation',
    valueInnovationDesc: 'Leveraging AI, real-time data, and agricultural science to deliver cutting-edge insights directly to farmers.',
    valueFarmerFirst: 'Farmer-First',
    valueFarmerFirstDesc: 'Every feature we build is designed with the farmer in mind — accessible, simple, and truly impactful.',
    valueTrust: 'Trust & Transparency',
    valueTrustDesc: 'We are committed to data privacy, honest recommendations, and building lasting trust with our farming community.',
    aboutJourneyTitle: 'Our Journey 🚀',
    aboutJourneySubtitle: 'A step-by-step development approach from planning to deployment.',
    phase1Label: 'Phase 1',
    phase1Event: 'Requirements Gathering & Analysis — Understand client needs, examine the competition, specify system features, and develop the technical solution. (Week 1 – Week 2)',
    phase2Label: 'Phase 2',
    phase2Event: 'System Design — Build the database schema, design the API, make wireframes for the UI, and implement the crop scoring logic. (Week 3 – Week 4)',
    phase3Label: 'Phase 3',
    phase3Event: 'Backend Development — Setup a Node.js / Express.js server with MongoDB schemas. Create REST APIs and setup JWT middleware. (Week 5 – Week 6)',
    phase4Label: 'Phase 4',
    phase4Event: 'Frontend Development — Creating UI components for a browser app, working on modules, incorporating API, adding bilingual support, and creating the Admin Panel with React.js. (Week 7 – Week 9)',
    phase5Label: 'Phase 5',
    phase5Event: 'Integration & Testing — API integration, end-to-end testing, authentication testing, ensuring responsive design, and bug fixing. (Week 10 – Week 11)',
    phase6Label: 'Phase 6',
    phase6Event: 'Documentation & Deployment — Develop, test, debug, and refine functionality; generate documentation, diagrams, and UI refinements; prepare presentation content; and conduct local deployments. (Week 12)',
    aboutTeamTitle: 'Meet the Team 👥',
    aboutTeamSubtitle: 'A passionate group of designers, developers, and ML engineers united by one goal.',
    member1Name: 'Manya Jain',
    member1Role: 'UI/UX Design',
    member1Bio: 'Crafting intuitive and visually compelling interfaces that make the Smart Yield experience seamless for every farmer.',
    member2Name: 'Divye Sharma',
    member2Role: 'Frontend + Backend Development',
    member2Bio: 'Architecting the full-stack foundation of Smart Yield — from responsive React interfaces to robust Node.js APIs and database design.',
    member3Name: 'Shaikh Niyaz',
    member3Role: 'Frontend + Backend Development',
    member3Bio: 'Building scalable server-side logic and dynamic frontend features that power the Smart Yield platform end-to-end.',
    member4Name: 'Sheraz Uddin',
    member4Role: 'ML Model Development',
    member4Bio: 'Developing and training the machine learning models that deliver accurate, data-driven crop recommendations to farmers.',
    aboutCtaTitle: 'Join Our Growing Community 🌱',
    aboutCtaSubtitle: 'Be part of the agricultural revolution. Start for free and see results in your very first season.',
    getStartedFree: 'Get Started Free',
    exploreServices: 'Explore Services',

    // Farm Analytics page
    farmAnalyticsPageTitle: 'AI Farm Analytics 📊',
    farmAnalyticsPageSubtitle: 'Upload your field photo — our AI analyzes soil, moisture & vegetation to recommend the best crops',
    comingSoonTitle: 'Unlocking AI Dashboard',
    comingSoonSubtitle: 'Preparing your intelligent farm analysis engine…',
    uploadFieldImage: 'Upload Your Field Image',
    uploadDesc: 'Take a photo of your field or upload from gallery. Our AI will analyze soil appearance, moisture levels, and vegetation.',
    dragDropText: 'Drag & drop your field image here',
    orClickUpload: 'or click to upload',
    supportedFormats: 'Supports JPG, PNG, WEBP — Max 10MB',
    analyzeField: 'Analyze My Field',
    analyzingField: 'AI is analyzing your field…',
    optionalLocation: 'Field Location (optional — for live weather)',
    enterDistrictOptional: 'Enter district name for live weather data',
    soilHealthScore: 'Soil Health Score',
    overallFieldScore: 'Overall Field Score',
    topCropMatches: 'Top Crop Matches',
    fieldConditions: 'Detected Field Conditions',
    soilMoisture: 'Soil Moisture',
    vegetationHealth: 'Vegetation Health',
    sunlightExposure: 'Sunlight Exposure',
    waterAvailability: 'Water Availability',
    landTexture: 'Land Texture',
    fertilityScore: 'Fertility Score',
    riskAlerts: 'Risk Alerts',
    smartFarmingTips: 'Smart Farming Tips',
    fertilizerRec: 'Fertilizer Recommendation',
    profitEstimation: 'Profit Estimation',
    expectedProfit: 'Expected Profit',
    perAcre: 'per acre',
    growingDuration: 'Growing Duration',
    matchScore: 'Match',
    voiceAssistant: 'Voice Assistant',
    listenRecommendation: 'Listen to Recommendation',
    uploadAnotherImage: 'Analyze Another Field',
    analysisComplete: 'Analysis Complete!',
    pestRisk: 'Pest Vulnerability',
    drySoilRisk: 'Dry Soil Risk',
    waterloggingRisk: 'Waterlogging Risk',
    lowFertilityRisk: 'Low Fertility Risk',
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    scanningImage: 'Scanning field image…',
    fetchingWeather: 'Fetching live weather…',
    runningAI: 'Running AI crop engine…',
    generatingReport: 'Generating your report…',
    detectedSoilType: 'Detected Soil Type',
    seasonalPrediction: 'Seasonal Crop Prediction',
    bestSeason: 'Best Season to Plant',
    irrigationAdvice: 'Irrigation Advice',
    
    // ML Pages
    yieldPredictionTitle: 'Smart Yield Prediction',
    yieldPredictionSubtitle: 'Powered by a Random Forest ML model to estimate expected crop production based on climate conditions.',
    diseaseDetectionTitle: 'Plant Disease Identifier',
    diseaseDetectionSubtitle: 'Upload a photo of a sick leaf. Our Computer Vision AI will analyze it to detect diseases and provide instant treatment recommendations.'
  },
  hi: {
    home: 'होम',
    dashboard: 'डैशबोर्ड',
    cropRecommendation: 'फसल सिफारिश',
    fertilizerGuide: 'उर्वरक गाइड',
    weather: 'मौसम जानकारी',
    askExpert: 'विशेषज्ञ से पूछें',
    login: 'लॉगिन',
    signup: 'साइन अप',
    logout: 'लॉगआउट',
    welcomeMessage: 'स्मार्ट फसल सलाहकार प्रणाली में आपका स्वागत है',
    heroTitle: 'स्मार्ट कृषि समाधानों के साथ किसानों को सशक्त बनाना',
    heroSubtitle: 'व्यक्तिगत फसल सिफारिशें, मौसम की जानकारी और विशेषज्ञ मार्गदर्शन प्राप्त करें',
    getStarted: 'शुरू करें',
    learnMore: 'और जानें',
    features: 'विशेषताएं',
    aboutUs: 'हमारे बारे में',
    contact: 'संपर्क',
    allRightsReserved: 'सर्वाधिकार सुरक्षित',

    // Footer
    brandName: 'स्मार्ट फसल सलाहकार',
    brandDesc: 'टिकाऊ खेती के लिए प्रौद्योगिकी-संचालित कृषि समाधानों के साथ किसानों को सशक्त बनाना।',
    quickLinks: 'त्वरित लिंक',
    adminLogin: 'एडमिन लॉगिन',
    servicesTitle: 'सेवाएं',

    // Dashboard
    advisoryTools: 'आपके सलाहकार उपकरण 🛠️',
    todaysTips: 'आज की खेती की सलाह 💡',
    tip1: 'पानी बचाने और फसल की पैदावार बढ़ाने के लिए सिंचाई से पहले मिट्टी की नमी जांचें',
    tip2: 'अपनी कृषि गतिविधियों की योजना बनाने के लिए नियमित रूप से मौसम पूर्वानुमान देखें',
    tip3: 'मिट्टी के स्वास्थ्य में सुधार और रासायनिक निर्भरता कम करने के लिए जैविक खाद का उपयोग करें',
    farmAnalytics: 'फार्म विश्लेषण',
    cropCalendar: 'फसल कैलेंडर',
    comingSoon: 'जल्द आ रहा है',
    stateLabel: 'राज्य',
    districtLabel: 'जिला',
    statusLabel: 'स्थिति',
    statusActive: '✅ सक्रिय',

    // Card descriptions
    cropRecommendationDesc: 'अपनी मिट्टी और स्थान के आधार पर AI-संचालित फसल सुझाव प्राप्त करें',
    fertilizerGuideDesc: 'इष्टतम NPK अनुपात और जैविक उर्वरक सिफारिशें',
    weatherDesc: 'वास्तविक समय मौसम अपडेट और 7-दिन का पूर्वानुमान',
    askExpertDesc: 'कृषि विशेषज्ञों से उत्तर प्राप्त करें',
    farmAnalyticsDesc: 'अपने खेत के प्रदर्शन और जानकारी को ट्रैक करें',
    cropCalendarDesc: 'अपनी कृषि गतिविधियों की योजना बनाएं',

    // Home page
    connectPeersDesc: 'पूरे भारत के किसानों के साथ चर्चा में शामिल हों',
    predictYield: 'उपज भविष्यवक्ता (ML)',
    predictYieldDesc: 'फसल उत्पादन का गणितीय अनुमान',
    detectDisease: 'पौध रोग पहचानकर्ता',
    detectDiseaseDesc: 'AI विकृति विश्लेषण के लिए पत्ते की तस्वीर अपलोड करें',
    empoweringTitle: 'भारत के किसानों को सशक्त बनाना 🇮🇳',
    empoweringDesc1: 'कृषि हमारे राष्ट्र की रीढ़ है, फिर भी किसानों को अक्सर फसल चयन, मौसम पैटर्न और उर्वरक उपयोग की समय पर जानकारी का अभाव है।',
    empoweringDesc2: 'हमारा मिशन प्रौद्योगिकी के साथ इस अंतर को पाटना है, किसानों को डेटा-आधारित अंतर्दृष्टि प्रदान करना जो उपज बढ़ाए, लागत कम करे और टिकाऊ खेती प्रथाओं को बढ़ावा दे।',
    featuresSubtitle: 'भारतीय किसानों के लिए विशेष रूप से डिज़ाइन किए गए उपकरण',
    ctaTitle: 'क्या आप अपनी खेती को बदलने के लिए तैयार हैं? 🌾',
    ctaSubtitle: 'हजारों किसानों के साथ जुड़ें जो पहले से स्मार्ट कृषि समाधानों से लाभ उठा रहे हैं',
    ctaButton: 'आज अपनी यात्रा शुरू करें',

    // Home feature descriptions
    cropRecommendationHomeDesc: 'अपनी मिट्टी के प्रकार और स्थान के आधार पर AI-संचालित फसल सुझाव प्राप्त करें',
    fertilizerGuideHomeDesc: 'इष्टतम NPK अनुपात और जैविक उर्वरक सिफारिशें',
    weatherHomeDesc: 'आपके क्षेत्र के लिए वास्तविक समय मौसम अपडेट और 7-दिन का पूर्वानुमान',
    askExpertHomeDesc: 'अपनी खेती के सवालों के लिए कृषि विशेषज्ञों से उत्तर प्राप्त करें',
    communitySupport: 'सामुदायिक समर्थन',
    communitySupportDesc: 'साथी किसानों से जुड़ें और सर्वोत्तम प्रथाओं को साझा करें',
    dataSecurity: 'डेटा सुरक्षा',
    dataSecurityDesc: 'आपका खेती डेटा हमारे साथ सुरक्षित और संरक्षित है',

    // CropRecommendation page
    cropPageTitle: 'फसल सिफारिश प्रणाली 🌱',
    cropPageSubtitle: 'अपनी मिट्टी और स्थान के आधार पर AI-संचालित फसल सुझाव प्राप्त करें',
    enterFarmDetails: 'अपनी खेत की जानकारी दर्ज करें',
    soilTypeLabel: 'मिट्टी का प्रकार',
    selectSoilType: 'अपनी मिट्टी का प्रकार चुनें',
    selectState: 'अपना राज्य चुनें',
    getCropRec: 'फसल सिफारिश प्राप्त करें',
    gettingRec: 'सिफारिशें प्राप्त हो रही हैं...',
    recommendedCrops: 'अनुशंसित फसलें 🌾',
    cropsFound: 'फसलें मिलीं',
    cropName: 'फसल का नाम',
    season: 'मौसम',
    waterReq: 'पानी की आवश्यकता',
    duration: 'अवधि',
    expectedYield: 'अपेक्षित उपज',
    cropRotationTip: 'सुझाव: मिट्टी के स्वास्थ्य को बनाए रखने और कीट प्रकोप को रोकने के लिए फसल चक्र अपनाएं। फसलों में विविधता बाजार के जोखिम को कम करने में भी मदद करती है।',

    // FertilizerGuide page
    fertPageTitle: 'उर्वरक गाइड 💧',
    fertPageSubtitle: 'इष्टतम NPK अनुपात और जैविक उर्वरक सिफारिशें प्राप्त करें',
    selectYourCrop: 'अपनी फसल चुनें',
    cropType: 'फसल का प्रकार',
    selectCropPlaceholder: 'उर्वरक सिफारिश के लिए फसल चुनें',
    getFertGuide: 'उर्वरक गाइड प्राप्त करें',
    gettingFertRec: 'सिफारिशें प्राप्त हो रही हैं...',
    npkRequirements: 'के लिए NPK आवश्यकताएं',
    nitrogen: 'नाइट्रोजन',
    phosphorus: 'फॉस्फोरस',
    potassium: 'पोटेशियम',
    organicFertRec: 'जैविक उर्वरक सिफारिश',
    organicManureTip: 'मिट्टी की संरचना और सूक्ष्मजीव गतिविधि में सुधार के लिए जैविक खाद डालें',
    applicationTips: '🌱 उपयोग के सुझाव:',
    fertTip1: 'बेहतर पोषक तत्व अवशोषण के लिए उर्वरक को विभाजित मात्रा में डालें',
    fertTip2: 'उर्वरक डालने से पहले मिट्टी में पर्याप्त नमी सुनिश्चित करें',
    fertTip3: 'संतुलित पोषण के लिए जैविक और रासायनिक उर्वरकों को मिलाएं',
    fertTip4: 'जड़ जलने से बचाने के लिए पौधे की जड़ से 5-7 सेमी दूर उर्वरक डालें',
    importantPrecautions: '⚠️ महत्वपूर्ण सावधानियां:',
    precaution1: 'उर्वरक डालने से पहले हमेशा मिट्टी की जांच करें',
    precaution2: 'अत्यधिक उर्वरक से बचें क्योंकि यह फसल और मिट्टी को नुकसान पहुंचा सकता है',
    precaution3: 'रासायनिक उर्वरक संभालते समय सुरक्षात्मक उपकरण पहनें',
    precaution4: 'उर्वरक को ठंडी, सूखी जगह पर नमी से दूर रखें',

    // Weather page
    weatherPageTitle: 'मौसम जानकारी 🌦️',
    weatherPageSubtitle: 'अपने क्षेत्र के लिए वास्तविक समय मौसम अपडेट और पूर्वानुमान प्राप्त करें',
    enterLocation: 'अपना स्थान दर्ज करें',
    districtName: 'जिले का नाम',
    enterDistrict: 'अपने जिले का नाम दर्ज करें',
    getWeather: 'मौसम जानकारी प्राप्त करें',
    gettingWeather: 'मौसम डेटा प्राप्त हो रहा है...',
    currentWeather: 'वर्तमान मौसम',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'वर्षा',
    forecast: '3-दिन का पूर्वानुमान',
    weatherFarmTip: 'खेती सलाह: मौसम पूर्वानुमान के आधार पर सिंचाई और छिड़काव की योजना बनाएं। बारिश से पहले कीटनाशकों का छिड़काव न करें।',

    // AskExpert page
    askPageTitle: 'विशेषज्ञ से पूछें 🎤',
    askPageSubtitle: 'अपनी खेती के सवालों के लिए कृषि विशेषज्ञों से उत्तर प्राप्त करें',
    submitQuery: 'अपना सवाल भेजें',
    expertResponseTime: 'हमारे कृषि विशेषज्ञ आपके सवाल की समीक्षा करेंगे और 24-48 घंटों में जवाब देंगे',
    yourName: 'आपका नाम',
    yourDistrict: 'जिला',
    yourQuestion: 'आपका सवाल',
    questionPlaceholder: 'अपनी कृषि समस्या विस्तार से बताएं। उदाहरण: मिट्टी की मिट्टी में गेहूं के लिए सबसे अच्छी सिंचाई विधि क्या है?',
    questionRequired: 'कृपया अपना सवाल दर्ज करें',
    questionMinLength: 'सवाल कम से कम 20 अक्षर का होना चाहिए',
    questionMaxLength: 'सवाल 1000 अक्षर से अधिक नहीं होना चाहिए',
    submittingQuery: 'सवाल भेजा जा रहा है...',
    submitToExpert: 'विशेषज्ञ को सवाल भेजें',
    betterResponsesTips: '💡 बेहतर जवाब के लिए सुझाव:',
    queryTip1: 'अपनी फसल, मिट्टी के प्रकार और क्षेत्र के बारे में विशिष्ट रहें',
    queryTip2: 'जो समस्या आ रही है उसका विवरण शामिल करें',
    queryTip3: 'जो तरीके आप पहले से आज़मा चुके हैं उनका उल्लेख करें',
    queryTip4: 'स्पष्ट उत्तर के लिए एक बार में एक मुख्य सवाल पूछें',
    faqTitle: 'अक्सर पूछे जाने वाले सवाल',
    faq1Q: 'जवाब मिलने में कितना समय लगता है?',
    faq1A: 'आमतौर पर 24-48 घंटों के भीतर। जरूरी सवालों को प्राथमिकता दी जाती है।',
    faq2Q: 'क्या मैं कई सवाल पूछ सकता हूं?',
    faq2A: 'हां, लेकिन हम बेहतर स्पष्टता के लिए प्रत्येक बार एक मुख्य सवाल पूछने की सलाह देते हैं।',
    faq3Q: 'मैं किस प्रकार के सवाल पूछ सकता हूं?',
    faq3A: 'कोई भी कृषि संबंधी सवाल: फसल चयन, कीट नियंत्रण, मिट्टी प्रबंधन, सिंचाई आदि।',
    querySuccessTitle: 'सवाल सफलतापूर्वक भेजा गया! 🎉',
    querySuccessDesc: 'आपका सवाल हमारे कृषि विशेषज्ञों को भेज दिया गया है। आपको 24-48 घंटों के भीतर आपके पंजीकृत संपर्क विवरण पर विस्तृत उत्तर मिलेगा।',
    gotIt: 'समझ गया!',
    
    // My Queries
    myQueriesTitle: 'आपके पिछले सवाल',
    statusPending: 'लंबित',
    statusAnswered: 'उत्तर दिया गया',
    adminResponse: 'विशेषज्ञ का उत्तर:',
    noQueriesFound: "आपने अभी तक कोई सवाल दर्ज नहीं किया है।",

    // Crop Calendar
    calendarPageTitle: 'फसल कैलेंडर',
    calendarPageSubtitle: 'महीने दर महीने अपनी कृषि गतिविधियों की योजना बनाएं',
    selectCropCalendar: 'फसल चुनें',
    cropCalendarPlaceholder: 'कैलेंडर देखने के लिए फसल चुनें',
    viewCalendar: 'कैलेंडर देखें',
    sowingPhase: 'बुवाई का चरण',
    growingPhase: 'बढ़ने का चरण',
    harvestingPhase: 'कटाई का चरण',
    activities: 'मुख्य गतिविधियां',
    noCalendarData: 'इस फसल के लिए कोई कैलेंडर डेटा उपलब्ध नहीं है।',

    // About page
    aboutOurStory: 'हमारी कहानी',
    aboutHeroTitle: 'स्मार्ट फसल सलाहकार के बारे में 🌾',
    aboutHeroSubtitle: 'भारत की कृषि विरासत के प्रति गहरे सम्मान और इस विश्वास से जन्मा कि प्रौद्योगिकी जीवन बदल सकती है — हम हर किसान के हाथों में सही जानकारी पहुँचाने के लिए यहाँ हैं।',
    aboutOurMission: 'हमारा मिशन',
    aboutMissionText: 'भारत के हर किसान को व्यक्तिगत, डेटा-आधारित अंतर्दृष्टि प्रदान करके कृषि ज्ञान को सुलभ बनाना — चाहे उनका स्थान, शिक्षा या संसाधन कुछ भी हो।',
    aboutOurVision: 'हमारी दृष्टि',
    aboutVisionText: 'एक ऐसा भविष्य जहाँ कोई भी भारतीय किसान समय पर सलाह के अभाव में फसल नुकसान से न जूझे। हम प्रौद्योगिकी को ग्रामीण कृषि में समानता लाने वाला माध्यम मानते हैं।',
    aboutImpactTitle: 'संख्याओं में हमारा प्रभाव 📊',
    statFarmersHelped: 'किसानों की मदद',
    statStatesCovered: 'राज्य कवर',
    statYieldIncrease: 'औसत उपज वृद्धि',
    statSatisfaction: 'संतुष्टि दर',
    aboutValuesTitle: 'हम किसके लिए खड़े हैं ✨',
    aboutValuesSubtitle: 'हमारे मूल मूल्य हमारे हर निर्णय और हर उत्पाद का मार्गदर्शन करते हैं।',
    valueSustainability: 'स्थिरता',
    valueSustainabilityDesc: 'हम पर्यावरण की रक्षा करते हुए उत्पादकता अधिकतम करने वाली पर्यावरण-अनुकूल खेती का समर्थन करते हैं।',
    valueInnovation: 'नवाचार',
    valueInnovationDesc: 'AI, वास्तविक समय डेटा और कृषि विज्ञान का उपयोग करके सीधे किसानों को अत्याधुनिक जानकारी पहुँचाना।',
    valueFarmerFirst: 'किसान प्रथम',
    valueFarmerFirstDesc: 'हम जो भी सुविधा बनाते हैं वह किसान को ध्यान में रखकर — सुलभ, सरल और वास्तव में प्रभावशाली।',
    valueTrust: 'विश्वास और पारदर्शिता',
    valueTrustDesc: 'हम डेटा गोपनीयता, ईमानदार सिफारिशों और हमारे किसान समुदाय के साथ स्थायी विश्वास बनाने के लिए प्रतिबद्ध हैं।',
    aboutJourneyTitle: 'हमारी यात्रा 🚀',
    aboutJourneySubtitle: 'योजना से तैनाती तक एक चरण-दर-चरण विकास दृष्टिकोण।',
    phase1Label: 'चरण 1',
    phase1Event: 'आवश्यकताएँ एकत्रण एवं विश्लेषण — ग्राहक की जरूरतें समझना, प्रतिस्पर्धा की जाँच करना, सिस्टम की विशेषताएँ निर्दिष्ट करना और तकनीकी समाधान विकसित करना। (सप्ताह 1 – सप्ताह 2)',
    phase2Label: 'चरण 2',
    phase2Event: 'सिस्टम डिज़ाइन — डेटाबेस स्कीमा बनाना, API डिज़ाइन करना, UI के लिए वायरफ्रेम बनाना और फसल स्कोरिंग तर्क लागू करना। (सप्ताह 3 – सप्ताह 4)',
    phase3Label: 'चरण 3',
    phase3Event: 'बैकएंड विकास — MongoDB स्कीमा के साथ Node.js/Express.js सर्वर सेटअप करना। REST APIs बनाना और JWT मिडलवेयर सेटअप करना। (सप्ताह 5 – सप्ताह 6)',
    phase4Label: 'चरण 4',
    phase4Event: 'फ्रंटेंड विकास — ब्राउज़र ऐप के लिए UI कॉम्पोनेंट बनाना, मॉड्यूल पर काम करना, API जोड़ना, द्विभाषी समर्थन जोड़ना और React.js के साथ एडमिन पैनल बनाना। (सप्ताह 7 – सप्ताह 9)',
    phase5Label: 'चरण 5',
    phase5Event: 'एकीकरण और परीक्षण — API एकीकरण, एंड-टू-एंड परीक्षण, प्रमाणीकरण परीक्षण, रेस्पॉन्सिव डिज़ाइन सुनिश्चित करना और बग ठीक करना। (सप्ताह 10 – सप्ताह 11)',
    phase6Label: 'चरण 6',
    phase6Event: 'दस्तावेज़ीकरण और तैनाती — कार्यक्षमता विकसित, परीक्षण, डीबग और परिष्कृत करना; दस्तावेज़, डायग्राम और UI सुधार तैयार करना; प्रस्तुति सामग्री तैयार करना और स्थानीय तैनाती करना। (सप्ताह 12)',
    aboutTeamTitle: 'हमारी टीम से मिलें 👥',
    aboutTeamSubtitle: 'एक लक्ष्य से एकजुट डिज़ाइनरों, डेवलपर्स और ML इंजीनियरों का जोशीला समूह।',
    member1Name: 'मान्या जैन',
    member1Role: 'UI/UX डिज़ाइन',
    member1Bio: 'सहज और आकर्षक इंटरफेस तैयार करना जो हर किसान के लिए Smart Yield अनुभव को सहज बनाते हैं।',
    member2Name: 'दिव्ये शर्मा',
    member2Role: 'फ्रंटेंड + बैकएंड विकास',
    member2Bio: 'Smart Yield की पूर्ण-स्टैक नींव तैयार करना — रिस्पॉन्सिव React इंटरफेस से मजबूत Node.js APIs और डेटाबेस डिज़ाइन तक।',
    member3Name: 'शेख नियाज़',
    member3Role: 'फ्रंटेंड + बैकएंड विकास',
    member3Bio: 'स्केलेबल सर्वर-साइड लॉजिक और डायनामिक फ्रंटेंड फीचर्स बनाना जो Smart Yield प्लेटफॉर्म को एंड-टू-एंड संचालित करते हैं।',
    member4Name: 'शेराज़ उद्दीन',
    member4Role: 'ML मॉडल विकास',
    member4Bio: 'मशीन लर्निंग मॉडल विकसित और प्रशिक्षित करना जो किसानों को सटीक, डेटा-आधारित फसल सिफारिशें प्रदान करते हैं।',
    aboutCtaTitle: 'हमारे बढ़ते समुदाय से जुड़ें 🌱',
    aboutCtaSubtitle: 'कृषि क्रांति का हिस्सा बनें। मुफ्त शुरू करें और अपने पहले ही मौसम में परिणाम देखें।',
    getStartedFree: 'मुफ्त शुरू करें',
    exploreServices: 'सेवाएं देखें',

    // Farm Analytics page
    farmAnalyticsPageTitle: 'AI फार्म विश्लेषण 📊',
    farmAnalyticsPageSubtitle: 'अपने खेत की फोटो अपलोड करें — AI मिट्टी, नमी और वनस्पति का विश्लेषण करके सर्वोत्तम फसलें सुझाएगा',
    comingSoonTitle: 'AI डैशबोर्ड खोला जा रहा है',
    comingSoonSubtitle: 'आपका बुद्धिमान खेत विश्लेषण इंजन तैयार हो रहा है…',
    uploadFieldImage: 'अपने खेत की फोटो अपलोड करें',
    uploadDesc: 'अपने खेत की फोटो लें या गैलरी से अपलोड करें। AI मिट्टी, नमी और वनस्पति का विश्लेषण करेगा।',
    dragDropText: 'खेत की फोटो यहाँ खींचें और छोड़ें',
    orClickUpload: 'या क्लिक करके अपलोड करें',
    supportedFormats: 'JPG, PNG, WEBP — अधिकतम 10MB',
    analyzeField: 'मेरे खेत का विश्लेषण करें',
    analyzingField: 'AI आपके खेत का विश्लेषण कर रहा है…',
    optionalLocation: 'खेत का स्थान (वैकल्पिक — लाइव मौसम के लिए)',
    enterDistrictOptional: 'लाइव मौसम डेटा के लिए जिला नाम दर्ज करें',
    soilHealthScore: 'मिट्टी स्वास्थ्य स्कोर',
    overallFieldScore: 'कुल खेत स्कोर',
    topCropMatches: 'शीर्ष फसल मिलान',
    fieldConditions: 'खेत की पहचानी गई स्थितियां',
    soilMoisture: 'मिट्टी की नमी',
    vegetationHealth: 'वनस्पति स्वास्थ्य',
    sunlightExposure: 'सूर्यप्रकाश',
    waterAvailability: 'पानी की उपलब्धता',
    landTexture: 'भूमि बनावट',
    fertilityScore: 'उर्वरता स्कोर',
    riskAlerts: 'जोखिम चेतावनियां',
    smartFarmingTips: 'स्मार्ट खेती सुझाव',
    fertilizerRec: 'उर्वरक सिफारिश',
    profitEstimation: 'लाभ अनुमान',
    expectedProfit: 'अपेक्षित लाभ',
    perAcre: 'प्रति एकड़',
    growingDuration: 'उगाने की अवधि',
    matchScore: 'मिलान',
    voiceAssistant: 'वॉइस असिस्टेंट',
    listenRecommendation: 'सिफारिश सुनें',
    uploadAnotherImage: 'दूसरे खेत का विश्लेषण करें',
    analysisComplete: 'विश्लेषण पूर्ण!',
    pestRisk: 'कीट संवेदनशीलता',
    drySoilRisk: 'सूखी मिट्टी का जोखिम',
    waterloggingRisk: 'जलभराव का जोखिम',
    lowFertilityRisk: 'कम उर्वरता का जोखिम',
    highRisk: 'उच्च जोखिम',
    mediumRisk: 'मध्यम जोखिम',
    lowRisk: 'कम जोखिम',
    scanningImage: 'खेत की फोटो स्कैन हो रही है…',
    fetchingWeather: 'लाइव मौसम डेटा मिल रहा है…',
    runningAI: 'AI फसल इंजन चल रहा है…',
    generatingReport: 'आपकी रिपोर्ट तैयार हो रही है…',
    detectedSoilType: 'पहचाना गया मिट्टी प्रकार',
    seasonalPrediction: 'मौसमी फसल भविष्यवाणी',
    bestSeason: 'बुवाई का सर्वोत्तम मौसम',
    irrigationAdvice: 'सिंचाई सलाह',

    // ML Pages
    yieldPredictionTitle: 'स्मार्ट उपज भविष्यवाणी',
    yieldPredictionSubtitle: 'जलवायु परिस्थितियों के आधार पर अपेक्षित फसल उत्पादन का अनुमान लगाने के लिए एक रैंडम फॉरेस्ट ML मॉडल द्वारा संचालित।',
    diseaseDetectionTitle: 'पौध रोग पहचानकर्ता',
    diseaseDetectionSubtitle: 'बीमार पत्ते की तस्वीर अपलोड करें। हमारा कंप्यूटर विज़न AI बीमारियों का पता लगाने और तत्काल उपचार की सिफारिशें प्रदान करने के लिए इसका विश्लेषण करेगा।'
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
